#!/bin/bash


BASEPATH="/reg/d/ana02"
INSTRUMENT="cxi"
EXPERIMENT="cxi35711"
FILEMASK="e86-r$1-s0*"

OUTPUTFILE="filelist_$1.txt"

FULLPATH=$BASEPATH/$INSTRUMENT/$EXPERIMENT/xtc/$FILEMASK

ls $FULLPATH > $OUTPUTFILE

echo "File list for run r"$1 " written to " $OUTPUTFILE

