#!/bin/tcsh


switch ($1)

        case feldkamp:
        rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . feldkamp@psexport.slac.stanford.edu:ana/
        breaksw

	case sellberg:
	rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . sellberg@psexport.slac.stanford.edu:~/CCA-2011/analysis/psana/
	breaksw

endsw
