#!/bin/bash

case $1 in

        "feldkamp" )
        	rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . feldkamp@psexport.slac.stanford.edu:ana/
        ;;

	"sellberg" )
		rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' --exclude 'arch' --exclude 'build' --exclude 'doc' . sellberg@psexport.slac.stanford.edu:~/CCA-2011/analysis/psana/
	;;

	"sellberg-build" )
		rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . sellberg@psexport.slac.stanford.edu:~/CCA-2011/analysis/psana/
	;;

	"dermen" )
		rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . dermen@psexport.slac.stanford.edu:~/psana_modules/
	;;

	"tjlane" )
		rsync -av  --exclude '.DS_Store' --exclude '.git*' --exclude 'ana.xcodeproj' --exclude '.sconsign.dblite' --exclude '.pkg_tree.pkl' . tjlane@psexport.slac.stanford.edu:~/opt/psana_modules/
	;;

	* )
		echo "Usage: $0 <argument>"
		echo "Allowed arguments include:"
		echo "   feldkamp"
		echo "   sellberg"	
	;;

esac

